name: Deploy to AWS ECS

on:
  push:
    branches:
      - master
      - develop
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Extract branch name
      id: extract_branch
      run:  echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Set environment variable
      run: node set-env.js
      env:
        BRANCH_NAME: ${{ env.BRANCH_NAME }}
        
    - name: Build Angular project
      run: npm run build -- --configuration production
      
    - name: Print branch name
      run: echo "Deploying branch $BRANCH_NAME"
